// Simple type definitions for our local data

import { z } from 'zod';

/**
 * Recursively remove .default() from a Zod schema
 * Used to create OpenAI-compatible schemas (OpenAI rejects $ref with sibling keywords like default)
 */
function deepRemoveDefaults(schema: z.ZodTypeAny): any {
  if (schema instanceof z.ZodDefault)
    return deepRemoveDefaults(schema.removeDefault());

  if (schema instanceof z.ZodObject) {
    const newShape: any = {};
    for (const key in schema.shape) {
      newShape[key] = deepRemoveDefaults(schema.shape[key]);
    }
    return new z.ZodObject({
      ...schema._def,
      shape: () => newShape,
    }) as any;
  }

  if (schema instanceof z.ZodArray)
    return z.ZodArray.create(deepRemoveDefaults(schema.element));

  if (schema instanceof z.ZodOptional)
    return z.ZodOptional.create(deepRemoveDefaults(schema.unwrap()));

  if (schema instanceof z.ZodNullable)
    return z.ZodNullable.create(deepRemoveDefaults(schema.unwrap()));

  return schema;
}

// CV-related Zod schemas (source of truth for validation)
// IMPORTANT: OpenAI Structured Outputs requires all fields to be REQUIRED
// We use .nullish().default(null) so:
// - Input type (CV data files): Fields are optional - can omit them
// - Output type (after parsing): Fields are required - always present as null
// - OpenAI schema: All fields required (always sent as null, not undefined)

export const ParagraphSchema = z.object({
  id: z.string().nullish().default(null),
  text: z.string(),
});

export const BulletPointSchema = z.object({
  id: z.string().nullish().default(null),
  iconName: z.string(),
  text: z.string(),
  url: z.string().nullish().default(null),
  description: z.string().nullish().default(null),
});

export const SubtitlesSchema = z.object({
  left: z.string().nullish().default(null),
  right: z.string().nullish().default(null),
  leftUrl: z.string().nullish().default(null),
  rightUrl: z.string().nullish().default(null),
});

export const CvSubSectionSchema = z.object({
  id: z.string().nullish().default(null),
  title: z.string().nullish().default(null),
  subtitles: SubtitlesSchema.nullish().default(null),
  paragraphs: z.array(ParagraphSchema).nullish().default(null),
  bulletPoints: z.array(BulletPointSchema).nullish().default(null),
});

export const CvSectionSchema = z.object({
  id: z.string().nullish().default(null),
  title: z.string().nullish().default(null),
  subtitles: SubtitlesSchema.nullish().default(null),
  paragraphs: z.array(ParagraphSchema).nullish().default(null),
  bulletPoints: z.array(BulletPointSchema).nullish().default(null),
  subSections: z.array(CvSubSectionSchema).nullish().default(null),
}).strict();

export const CVSettingsSchema = z.object({
  on: z.boolean(),
  name: z.string(),
  subtitle: z.string(),
  mainColumn: z.array(CvSectionSchema),
  sideColumn: z.array(CvSectionSchema),
  profilePicture: z.string().nullish().default(null),
});

// OpenAI-compatible schema (auto-generated by removing .default())
// Used only for zodResponseFormat calls - ensures OpenAI validates the structure
export const CVSettingsSchemaForOpenAI = deepRemoveDefaults(CVSettingsSchema);

// Parsed types (after Zod parsing - all optional fields become required with null)
// These are the only types used throughout the app - data is parsed immediately on load
export type Paragraph = z.infer<typeof ParagraphSchema>;
export type BulletPoint = z.infer<typeof BulletPointSchema>;
export type Subtitles = z.infer<typeof SubtitlesSchema>;
export type CvSubSection = z.infer<typeof CvSubSectionSchema>;
export type CvSection = z.infer<typeof CvSectionSchema>;
export type CVSettings = z.infer<typeof CVSettingsSchema>;

export type Settings = {
  mainPage?: {
    title?: string;
    subtitles?: string[];
    mainImage?: string;
    metadataDescription?: string;
  };
  metadata?: {
    title?: string;
    description?: string;
    keywords?: string;
  };
  social?: Link[];
  specialPages?: {
    chatbot: boolean;
  };
};

export type StylesSettings = {
  theme?: string;
  font?: string;
};

export type Project = {
  title: string;
  slug: string;
  image: string;
  tags: string[];
  links: Link[];
  featured: boolean;
  description?: string;
  order?: number;
};

export type Gallery = {
  title: string;
  filteringIsEnabled?: boolean;
};

export type Link = {
  title: string;
  url: string;
  iconName: string;
};